### PR TITLE
Run tests in the browser as well

### PR DESCRIPTION
**Pull request by XVincentX**
This small PR will ensure that all current tests will be run in a browser instance using `karma`

### CODE REVIEW

**Comment by pksunkara** [comment]
:scream:

Small question. Why do we need to test this since we are not using this library in the browser?

**Comment by XVincentX** [comment]
@pksunkara 
Basically because we will need minim in the browser very soon. We will use it to render MSON attributes in the documentation with the new AST.

**Comment by smizell** [comment]
Ping @danielgtaylor

**Comment by danielgtaylor** [comment]
@XVincentX @pksunkara @smizell what do you think of only running the frontend tests on the CI hosts (or using phantomjs locally)? Having a Firefox window pop up every time that I run `npm test` is a bit jarring.

**Comment by pksunkara** [comment]
I agree with you.

**Comment by smizell** [comment]
@danielgtaylor There is a command for running just Node tests, added by @XVincentX in this request. This means that `npm test` runs all of the tests, while other commands are provided to do subsets of tests (such as `npm nodejstests`). 

I'm fine making frontend tests run on CI only if that would be best for everyone.

**Comment by danielgtaylor** [comment]
Yeah I think this is probably fine. I'll just run `npm run nodejstests` for now and if it gets to be a problem I'll submit a PR to make the frontend tests only run on the CI hosts.

**Comment by smizell** [comment]
:+1:

**Pull request merged**
