### PR TITLE
Update uptown to latest version

### PR DESCRIPTION
**Pull request by XVincentX**

### CODE REVIEW

**Comment by smizell** [comment]
I've published 0.14.1 of Minim that has the updated Uptown.

But... Minim uses Lodash 3.10.1. :)

**Comment by smizell** [comment]
I noticed this too late.

**Comment by XVincentX** [comment]
Can we update this one as well?

**Comment by smizell** [comment]
Definitely. I just didn't have time for it at the time. I'll check it tonight.

**Comment by XVincentX** [comment]
Thanks a lot!

**Pull request merged**
